# Generated by Django 5.2.7 on 2025-11-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_hospital_email_remove_hospital_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='address',
            field=models.TextField(default='Unknown'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hospital',
            name='device_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='phone',
            field=models.CharField(default='0000000000', max_length=15),
            preserve_default=False,
        ),
    ]
