# Generated by Django 5.2.7 on 2025-11-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_hospital_latitude_hospital_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='device_token',
        ),
        migrations.AlterField(
            model_name='hospital',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
