# Generated by Django 5.2.7 on 2026-01-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0003_remove_hospital_address_remove_hospital_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='location',
            field=models.CharField(default='Unknown', max_length=200),
        ),
    ]
