# Generated by Django 5.2.7 on 2025-11-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
