# Generated by Django 5.2.7 on 2025-11-26 18:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidentapp', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='nearest_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.hospital'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='severity',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='accident',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Hospital',
        ),
    ]
