# Generated by Django 5.2.7 on 2025-11-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidentapp', '0002_alter_accident_nearest_hospital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='alert_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accident',
            name='severity',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=20),
        ),
    ]
