# Generated by Django 5.2.7 on 2025-11-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidentapp', '0003_accident_alert_sent_alter_accident_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='handled',
            field=models.BooleanField(default=False),
        ),
    ]
