# Generated by Django 5.2.7 on 2025-11-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidentapp', '0004_accident_handled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
