# Generated by Django 5.2.7 on 2025-11-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidentapp', '0005_alter_accident_latitude_alter_accident_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='accident',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
